# Rule_ID:510
# @title [Catalog] property is an absolute URI 
# @tag dataset

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>


SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o 
WHERE {
  ?s a dcat:Catalog.
  ?s ?p ?o.
  FILTER( ?p in (foaf:homepage, dct:language, dct:rights, dct:license, dcat:themeTaxonomy, dct:hasPart, dct:isPartOf )).
  filter ( ! ( isIRI(?o) )) .
  BIND (dcat:Catalog AS ?o).
  BIND ("Catalog" AS ?Class_Name).
  BIND (510 AS ?Rule_ID).
  BIND ("warning" AS ?Rule_Severity).
  BIND ("Catalog property should be an absolute URI ." AS ?Rule_Description).
  BIND (concat("The property ", str(?p) ," of dcat:Catalog ",str(?s)," should be an absolute URI.") AS ?Message).
}
