# Rule_ID:413
# @title [ContactPoint] vcard:hasEmail is a URI 
# @tag dataset

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o ?Rule_Auxillary
WHERE {
  ?s a dcat:Dataset.
  ?s dcat:contactPoint ?cPoint.
  ?cPoint vcard:hasEmail ?email.
  filter ( ! ( isIRI(?email))) .
  BIND (vcard:hasEmail AS ?p).
  BIND (dcat:Dataset AS ?o).
  BIND ("Kind" AS ?Class_Name).
  BIND (413 AS ?Rule_ID).
  BIND ("error" AS ?Rule_Severity).
  BIND ("vcard:hasEmail for a contactpoint of a Dataset is a URI" AS ?Rule_Description).
  BIND (concat("The vcard:hasEmail of contactpoint of dcat:Dataset ",str(?s)," is not a URI.") AS ?Message).
  BIND ("vodap" AS ?Rule_Auxillary).  
}
