version: '2'
services:
  webservice:
    build:
      context: ./webservice
    extra_hosts:
      - "opendata.vlaanderen.be:127.0.0.1"
    labels:
      webservice: "VODAP frontend access"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs:/logs
      - ./webservice/www:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - datashared
    environment:
      - ENV_URI_DOMAIN=opendata.vlaanderen.be
      - ENV_SPARQL_ENDPOINT_SERVICE_URL=http://vodapweb-virtuoso:8890/sparql
    links:
      - vodapweb-virtuoso:vodapweb-virtuoso
      
  vodapweb-virtuoso:
    image: tenforce/virtuoso
    ports:
      - '8890:8890'
      - '1111:1111'
    labels:
      virtuoso: "VODAP temporary database store"    
    environment:
      - DBA_PASSWORD=vodap
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://data.vlaanderen.be/id/dataset/default
    volumes:
      - ./virtuoso:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - datashared

  datashared:
    image: busybox
    volumes:
      - ./data:/data
