PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX vodap: <http://data.vlaanderen.be/ns/vodap#>

SELECT DISTINCT ?publisherid ?name where {
  ?dataset vodap:ckan-organisation ?publisherid .
  ?dataset vodap:ckan-organisation-name ?name .
} ORDER BY ?name
